Convert more queries to use graphql variables
seermedical/seer-py pull request #110
Opened 2020-10-09 06:19 UTC by bjdoyle

Converts more queries to use graphql variables rather than python string formatting.
In particular, all queries which use get_paginated_response have been converted.
Also adds test utility methods which make testing queries which use get_paginated_response easier, cutting out a lot of boilerplate.

Also includes a change to the query string for get_diary_insights as the existing one was found to not be consistent with the current schema.

As well as test methods, all changed queries have been tested live against the api, with the exception of get_study_ids_in_study_cohort and get_user_ids_in_user_cohort, for which I could not find suitable data to test against.

Further improvements to testing are required, in particular that the interpolation of variables is not tested in the current tests as that happens when the query is run, which is currently mocked. I have not fixed that in this PR, I am still thinking of a way to do it. It would also be good to have integration tests which run the queries against actual data but again that is a job for the future.

2020-10-11 22:11 UTC, seerwill requested changes
Looks good on the whole. There are some instances where optional fields are marked as required which I have noted. I think in most cases this will be OK as going this way won't be an error (marking a required field as optional will cause a schema validation error). However I think for the most part we should accept omitted fields for things like `fromTime` / `toTime` to prevent the need for dummy values like `90000000000`. 

There are also a few areas I flagged where using `Range` rather than separate from/to times would make the query much easier to use and more flexible. Would require a bit of rewriting the functions in `seerpy.py` so probably beyond the scope of this PR.

I agree integration testing would be nice here as its hard to tell just from looking at the schema and the JSON test files whether the queries will fail against the real API.

2020-10-11 22:11 UTC, seerwill commented on tests/test_seerpy.py
> +        # TODO: There is a mis-match between the fields in the query and the schema in graphiql
The schema is the source of truth. The API has been evolving and we haven't gotten around to updating seerpy yet.

2020-10-11 22:11 UTC, seerwill commented on tests/test_seerpy.py
> +    def check_paginated_query(cls, seer_connect, function_to_test, function_args=None,
Nice work, this makes things a lot cleaner on the testing side!

2020-10-11 23:52 UTC, bjdoyle commented on seerpy/graphql.py
> +            users(limit: $limit, offset: $offset) {
Wouldn't that change as is fail? I'd rather this go in a separate PR if it's required - this is only meant as a conversion to using variables as far as possible.

2020-10-11 23:55 UTC, bjdoyle commented
@seerwill I've accepted some of your suggestions, made some changes in response to others. I don't want to make changes in this PR that go beyond converting existing queries as-is to use query variables, as far as that has been possible, so some others I have not changed.

2020-10-12 00:00 UTC, seerwill commented on seerpy/graphql.py
> +            users(limit: $limit, offset: $offset) {
I don't think it would fail, but I could be wrong I just edited through github. I think it's more that the current format suggests you can omit `$user_cohort_id` which is not true. 

Happy for this to be in a separate PR I don't think its urgent.

2020-10-12 00:01 UTC, seerwill commented
> I don't want to make changes in this PR that go beyond converting existing queries as-is to use query variables

Makes sense, I think this PR has just highlighted some of the odd parts of the code base, so I though it was worth noting.

2020-10-12 00:21 UTC, seerwill requested changes
Commit 61f88c39981b386cdd5d53fa11c1fb2a29cb756a will have to be reverted I believe, but other than that looks basically good to go.

P.S. I think this is a good example of code that will pass unit testing but fail integration tests when they are written.

2020-10-12 00:21 UTC, seerwill commented on seerpy/graphql.py
> +                         $to_duration: Float) {
I suspect this change will error out. The type in the schema for ranges is `Float!`, it's the `Range` itself that is optional. As the query hard codes `labels(ranges:...` then the floats are required to be populated.

For the purposes of this PR as you aren't planning to construct ranges in the python code, then these should be left as mandatory.

2020-10-12 00:21 UTC, seerwill commented on seerpy/graphql.py
> +                                  $to_time: Float) {
Similar here, `Range` is optional, these are are required.

2020-10-12 00:21 UTC, seerwill commented on seerpy/graphql.py
> +                                  $to_time: Float) {
Same as above

2020-10-12 00:45 UTC, seerwill approved these changes
👍

2020-10-12 00:51 UTC, merged