Filter diary labels by tags 2
seermedical/seer-py pull request #117
Opened 2020-10-22 00:44 UTC by dkeden

This PR modifies the strategy to filter diary labels. 

Previously, the `get_diary_labels` query used an API-based filter on `labelGroups` (i.e. filters by `labelType`). Unfortunately, `labelGroups` are based on a question when a user creates an account, rather than the labels themselves. In order to retrieved all labels of a specific type, e.g. "Seizure", "Cardiac" or "Event", the only current way is to manually filter by `tagType` value. 

It would be ideal to modify / add a filter in the API to filter this instead.

Second attempt.

2020-10-22 03:50 UTC, seerwill requested changes
There don't appear to be any tests checking filtering across multiple label groups? It might be worth adding something along these lines.

2020-10-22 03:50 UTC, seerwill commented on seerpy/seerpy.py
> +    def get_diary_labels(self, patient_id, label_type='all', tag_type='seizure', offset=0, limit=100, from_time=0,
Have you confirmed that `label_type='all'` works as expected?

2020-10-22 03:50 UTC, seerwill commented on seerpy/seerpy.py
> +            'cardiac', 'other'.
```suggestion
            The type of label to retrieve. Default = 'seizure'. Options = 'seizure',
            'cardiac', 'other'. Filters client-side using label tags.
```

2020-10-22 03:50 UTC, seerwill commented on seerpy/seerpy.py
> +                    label_results = response
Wouldn't this have undesirable results if for instance the first labelGroup has labels, but the second labelGroup doesn't? i.e. wouldn't it "reset" the `label_results` variable?

```suggestion
                    continue
```

2020-10-22 03:50 UTC, seerwill commented on seerpy/seerpy.py
> +                    if any(tag['tagType']['value'] == tag_type.capitalize() for tag in label['tags']):
@bjdoyle 's comment from #115

> it would be better to do this the other way around and take the lower of the tag.

2020-10-22 03:50 UTC, seerwill commented on seerpy/seerpy.py
> +    def get_diary_labels_dataframe(self, patient_id, label_type='seizure', offset=0, limit=100,
I think its a bit confusing to have different defaults on these two queries. I'd set the default on both to `all`?

2020-10-22 03:50 UTC, seerwill commented on tests/test_seerpy.py
> +class TestGetDiaryLabels:
Is there a way to integrate these tests with the pagination approach used above?

2020-10-26 01:04 UTC, dkeden commented on seerpy/seerpy.py
> +    def get_diary_labels_dataframe(self, patient_id, label_type='seizure', offset=0, limit=100,
Thanks for pointing this out. Do you mean between between `get_diary_labels` `get_diary_labels_dataframe`? My preference would be to have both `label_type=all` and `tag_type=seizure` in both functions so that we don't break pre-existing code (as you mentioned) for filtering on `label_type`

2020-10-26 01:05 UTC, dkeden commented on tests/test_seerpy.py
> +class TestGetDiaryLabels:
We don't actually paginate the diary labels, it's more of a 'manual' method, so not sure if we can? Or do you mean to develop a test that tests the fake pagination?

2020-10-26 01:07 UTC, dkeden commented on seerpy/seerpy.py
> +    def get_diary_labels(self, patient_id, label_type='all', tag_type='seizure', offset=0, limit=100, from_time=0,
Not other than in graphql, but I'd imagine that this would (or, should) be an API test? I've seen both "seizures" and "medications" `labelGroups` returned, etc.

2020-10-26 01:16 UTC, dkeden commented on seerpy/seerpy.py
> +                    continue
Yeah, good point

2020-10-26 01:16 UTC, dkeden commented on seerpy/seerpy.py
> +                    continue
I guess it means we may end up with an empty dict of "medication" `labelGroups`, but I don't think that's a big issue if we'll change this in the API at some point

2020-10-26 01:21 UTC, seerwill commented on seerpy/seerpy.py
> +    def get_diary_labels_dataframe(self, patient_id, label_type='seizure', offset=0, limit=100,
Yes, I think using `all` is the best approach.

2020-10-26 01:56 UTC, dkeden commented on seerpy/seerpy.py
> +                            filtered_labels.append(label)
@seerwill I've modified this so that `[]` isn't returned, and the outer structure / response with an empty field on `labels` is returned. A test to cover this would be good at some point, I can put it on my TODO?

2020-10-27 03:16 UTC, bjdoyle commented on seerpy/seerpy.py
> +                label_results['labelGroups'][idx]['numberOfLabels'] = len(filtered_labels)
limit is the page size you shouldn't have to worry about it.

2020-10-27 03:17 UTC, bjdoyle commented on seerpy/seerpy.py
> +                label_results['labelGroups'][idx]['numberOfLabels'] = len(filtered_labels)
but I don't think it matters if you filter as you go or at the end.

2020-10-27 03:32 UTC, seerwill requested changes
Still a few issues with tests and defaults on queries I think need to be resolved before merging.

2020-10-27 03:32 UTC, seerwill commented on seerpy/seerpy.py
> +                        filtered_labels.append(label)
```suggestion
                            filtered_labels.append(label)
```

Missing indentation?

2020-10-27 03:32 UTC, seerwill commented on seerpy/seerpy.py
> +    def get_diary_labels_dataframe(self, patient_id, label_type='all', tag_type='seizure', offset=0, limit=100,
As above - this changes the default behaviour. It would be good to have an "all" option for tag_types

2020-10-27 03:32 UTC, seerwill commented on tests/test_data/diary_labels_2.json
> +                                    "value": "Cardiac"
As this is a `cardiac` label, we don't know if the second request is merged in to the first with the `test_get_diary_labels` test below. It would be better to mark this as seizure and check for two labels in the result?

2020-10-27 03:32 UTC, seerwill commented on tests/test_seerpy.py
> +class TestGetDiaryLabels:
I don't see a test here for merging multiple labelGroups (unless this is covered by existing tests somewhere?). As this is a more important aspect of the query now I think this should be covered by testing. 

(Sorry, I thought I'd commented on this previously but I can't seem to find the comment any more 🤷‍♂️)

2021-09-15 02:22 UTC, closed without merging