Add script to download studies in Examples folder
seermedical/seer-py pull request #121
Opened 2020-11-30 03:13 UTC by dkeden

This is a modified version of `msg_data_downloader.py` in the Examples folder. By default, all studies, channel groups and channels are downloaded, unless a specific channel group is specified on input.

This script could be developed if there is a need for it in the future.

2020-11-30 07:52 UTC, bjdoyle requested changes

2020-11-30 07:52 UTC, bjdoyle commented on Examples/downloader/downloader.py
> +                    continue
```suggestion
            if channel_group_to_download and channel_group != channel_group_to_download:
                continue
```

2020-11-30 07:52 UTC, bjdoyle commented on Examples/download_studies.py
> +    return studies_file
It would be better to get this function to return the dict, then you wouldn't need to write the empty file, just return an empty dict if the file doesn't exist, or return the json from the file if it does.

2020-11-30 07:52 UTC, bjdoyle commented on Examples/download_studies.py
> +    study_ids = [study_id for study_id in download_status if download_status[study_id] == 0]
```suggestion
    study_ids = [study_id for study_id in download_status if not download_status[study_id]]
```

2020-11-30 07:52 UTC, bjdoyle commented on Examples/download_studies.py
> +        except ReadTimeoutError:
If you are downloading multiple studies this will re-download previous studies if there is an error on any study after the first one. You either need to have this except statement inside the for study_id in study_ids loop, or you need to do the check for whether a study has been downloaded already in the for loop.

2020-12-14 05:20 UTC, dkeden commented on Examples/download_studies.py
> +        except ReadTimeoutError:
Hey @bjdoyle, could you please let me know what you think of the most recent change? Would I need to move the `if attempts == 5` line to inside the `except` statement?

2020-12-16 22:47 UTC, dkeden commented
Hey @norrishd, any chance you could review this? Brendan is away until tomorrow, and am hoping to have this script available today! No worries if not, let me know

2020-12-17 23:53 UTC, norrishd approved these changes
Made a bunch of comments but maybe they're all overkill.

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +        output_dir = join(dirname(__file__), 'data')
I wonder if it would be more intuitive to a new user for the data to default to downloading to `~/data` i.e. in their current directory rather than putting it in `seer-py/Examples/data`?

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +    studies_file = join(dirname(__file__), 'studies.json')
Similar to a comment below, it might be better not to download data into a version-controlled directory (the ol' "separate your data from your source files" maxim). The usual approach I've encountered with other packages is they create a public or private folder in the user's home directory and store stateful stuff in there, e.g. maybe `~/seerpy`.
https://stackoverflow.com/a/4028943/8822495

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +def get_download_status_file(client):
One risk here is that study IDs get downloaded once then never again, so if/when new studies get created, the user won't be able to download them and might not understand why.

If this is just intended as a one-off script that's probably fine, otherwise it might be worth adding another `argparse` flag to force re-download of study IDs, which can get passed to this function and handled.

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +                    client = SeerConnect()
This is more for my own edification, but what's the advantage in re-instantiating a `SeerConnect()` with each timeout?

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +                download_status[study_id] = 1
If this script is invoked once with `--channelgroup eeg` (or whatever is valid) then re-run with a different channel group, won't download anything.

What if the `download_status` file instead stored e.g.
```
status = {
    study_id1: ['eeg', 'ecg', ... ],
    study_id2: ['eeg', 'ecg', ... ]
}
```
Again maybe this is just meant to be a quick and dirty script, in which case all good!

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +                    time.sleep(1)
I've never come across `sys.stdout.write/flush`, but for me when I execute these lines in a script I get all on one line:
```ReadTimeoutError. Re-trying after a short break... 5ReadTimeoutError. Re-trying after a short break... 4ReadTimeoutError. Re-trying after a short break... 3ReadTimeoutError. Re-trying after a short break...```

Is that the intention?

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +                    time.sleep(1)
Oh I get it!
https://stackoverflow.com/a/10019596/8822495

That's so interesting, I remember noticing on Ubuntu that if you do:
```python
for i in range(5):
    print(i, end='')
    time.sleep(1)
```
It sits there for 5 seconds then prints it all at once. I always thought this was a bug with the `end` param. But I guess you're addressing this kind of issue that crops up on some systems?

What if the "ReadTimeoutError. Re-trying after a short break..." was printed on its own line before the loop, then in the loop just `str(i)` is printed?

2020-12-17 23:53 UTC, norrishd commented on Examples/download_studies.py
> +        if attempts == 5:
Out of curiosity how common are timeouts? Does it ever timeout 2 or 3 times then make it on the 4th/5th try?

2022-03-02 03:33 UTC, closed without merging