Resolves #130 : Limit max items returned in paginated query
seermedical/seer-py pull request #132
Opened 2021-03-22 23:33 UTC by ronrest

I have added the `max_items` parameter to the following functions.

```python
get_paginated_response()

get_studies()
get_studies_dataframe()
get_patients()
get_mood_survey_results()
get_mood_survey_results_dataframe()
get_labels()
get_labels_dataframe()
get_diary_insights()
get_user_ids_in_user_cohort()
get_study_ids_in_study_cohort()
get_diary_study_labels()
get_diary_study_labels_dataframe()
```

## Ommited

I have not added `max_items` to the following functions

```python
get_organizations()                 # number of organizations is too few, so didnt implement
                                    # pagination
get_organisations_dataframe()

get_all_bookings()                  # Underlying GraphQL query for Bookings does not support
                                    # pagination. But i did allow  for a `includeCancelled` option
                                    # to be used
get_all_bookings_dataframe()        # As above

get_diary_study_label_groups()      # As per a TODO comment in the function, its unlikely that we
                                    # will get more than 20 items
get_diary_study_label_groups_dataframe() # As above

get_diary_labels()                  # Contains nesting that would make it unintuitive to use
                                    # `max_items`
                                    # eg, for each user, the results can contain contain multiple
                                    # `labelGroups` and for each `labelGroup` there can be multiple
                                    # `labels`
get_diary_labels_dataframe()        # As above

get_diary_medication_alerts()       # Contains nesting that would make it unintuitive to use
                                    # `max_items`
                                    # multiple items at the ["alerts"] level
                                    # multiple items at the ["alerts", "labels"] level
                                    # multiple items at the ["alerts", "labels", "doses"] level
get_diary_medication_alert_windows()# Contains nesting that would make it unintuitive to use
                                    # `max_items`
                                    # multiple items at ["alerts"] level
                                    # multiple items at ["alerts", "windows"] level
```

Also, ones that we could potentially add the option to in the future

```python
get_diary_study_channel_groups()    # currenlty it runs as a single query call.
                                    # how many channel groups are there for diary studies?
                                    # could it benefit from having a max_limit

get_diary_study_channel_groups_dataframe() # As above
```

## Testing

I have performed some preliminary sanity checks on the following:

```python
get_studies()
get_studies_dataframe()
get_patients()
get_mood_survey_results()
get_mood_survey_results_dataframe()
```

Ones I havent tested so far

```python
get_labels()
get_labels_dataframe()

get_diary_insights()                # Havent found any records with diary insights to check
get_user_ids_in_user_cohort()       # Havent found any any cohort ids to check
get_study_ids_in_study_cohort()     # havent found any study cohort ids to check

get_diary_study_labels()            # havnt found any patients with diary study labels to check
get_diary_study_labels_dataframe()  # as above
```

2021-03-24 05:56 UTC, norrishd requested changes
Awesome work and thanks for the proactive approach in improving the repo!

I've made a number of changes, most of them small nit-picky things.

However more importantly, a number of the tests failed on Buildkite - https://buildkite.com/seer-medical/seer-py/builds/658#9195c5c2-7e8e-4729-839c-8d8cb932753f

I'm not sure if they're due to your changes to `get_paginated_response()` or were previously failing and no one noticed, but would you be able to double check?

2021-03-24 05:56 UTC, norrishd commented on seerpy/graphql.py
> +ORGANIZATION_BOOKINGS = """
IMO this is a good improvement over `get_bookings_query_string()`. I have a couple of uncertainties:

1. Maybe it's a bit fraught to allow null values for `startTime` and `endTime`? There are thousands of bookings, and with no pagination as well...
1. Did you tune in for the workshop on the new "resources" schema? It allows for pagination for bookings, and if we're going to update queries in `seer-py` I think @cheewee-seer would approve of us switching to the new schema. That might be a slightly bigger piece though...

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +            iteration, so we set `object_path=["user"]`. But we actually want
Nits: "e.g." is used just above, so would be good to be consistent throughout the documentation.

The example is really helpful, though I'm a tiny bit confused by the comment - is it giving two different examples? "But we actually" reads to me like the first prescription is actually wrong. Maybe a slight rephrasing to "If we are interested in... If we instead want to iterate through..."

Also there's a double space with "survey  information" :-)

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +            max number of items to return. In the case of queries containing
More nits: Probably good to capitalise the first word ("Max") to be consistent with the documentation of other args. This goes for all the other methods where `max_items` has been added.

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +        variable_values = deepcopy(variable_values) # prevent local changes affecting external one
Nits: PEP likes two spaces before in-line comments. Ditto the comment just below

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +            # print(f"items: {len(response)}  limit: {limit}  fetched: {total_items_returned} remain: {remaining_items}") # for debuging purposes
Accidentally left this in!

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +    def get_patients(self, party_id=None, limit=50, max_items=None):
Did you do any experimenting with whether 50 is a good size? My intuition is that we could probably go a fair bit higher to improve performance, though I'm not sure who to check this with.

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +        # TODO: request changes to seer-api so we can perform pagination
See my other comment - we can perform pagination :-)

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +        # response = self.execute_query(query_string)
Good not to leave commented-out code in there

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +    def get_all_bookings(self, organisation_id, start_time, end_time, include_cancelled=False):
Do you know if the previous default would have implicitly been `True` for including cancelled bookings? If so this means a breaking change for consumers, so we'd need to bump the major version number. If it's not breaking we should bump the minor version number as new functionality has been added (in _setup.py_) - https://semver.org/

2021-03-24 05:56 UTC, norrishd commented on seerpy/seerpy.py
> +        query_string = graphql.ORGANIZATION_BOOKINGS
Subjective opinion: could just pass this into the `execute_query()` call without first assigning to a variable? Your call though, I don't really mind.

2021-03-24 05:56 UTC, norrishd commented on seerpy/utils.py
> +    bool
What is the purpose of adding this function? I can't see anywhere else in the repo that it's used.

2021-03-24 05:56 UTC, norrishd commented on seerpy/utils.py
> +    d: dict
A more descriptive variable name than `d` would be good. I know it's extremely obvious what it is, and there's an immediate description, but it's a general good practice.

2021-03-24 05:56 UTC, norrishd commented on seerpy/utils.py
> +    *keys:
Would it be safer/clearer for this to take a list of str? IDK if there's any risk of `allow_missing_keys` and `default` being mixed in with the other keys - there might not be, in which case feel free to delete this comment!

2021-03-24 05:56 UTC, norrishd commented on seerpy/utils.py
> +        Allow travering along missing keys? If so, this acts like the
"traversing"

2021-04-07 07:57 UTC, ronrest commented on seerpy/utils.py
> +    *keys:
I dont think there is a danger of that, `allow_missing_keys` and `default` need to be passed in as keyword arguments. But, as you say,  it is perhaps cleaner to have the keys as a list of strings. It will allow a user to pass a variable containing the list of keys without having to prefix it with a `*` to unpack the values.

2021-04-07 07:58 UTC, ronrest commented on seerpy/utils.py
> +    *keys:
fixed this

2021-04-07 07:58 UTC, ronrest commented on seerpy/utils.py
> +        Allow travering along missing keys? If so, this acts like the
fixed this

2021-04-07 08:00 UTC, ronrest commented on seerpy/utils.py
> +    d: dict
This is a tricky one. 

- I cant have it as `dict` because that is a reserved name. 
- I changed it to `dct`, which im not sure is really any better than just `d`
- I could have something like `input_dict`, but then it starts to get a bit too verbose

Do you have any other suggestions for the name?

2021-04-07 08:02 UTC, ronrest commented on seerpy/utils.py
> +    bool
Was essentially there for testing that a function throws the expected Error. But unnecessary now that you have pointed out the `pytest` library.

Deleted this function

2021-04-07 08:06 UTC, ronrest commented on seerpy/seerpy.py
> +        query_string = graphql.ORGANIZATION_BOOKINGS
I think it keeps it consistent with all the other functions to have this.

2021-04-07 08:07 UTC, ronrest commented on seerpy/seerpy.py
> +            # print(f"items: {len(response)}  limit: {limit}  fetched: {total_items_returned} remain: {remaining_items}") # for debuging purposes
fixed

2021-04-08 00:12 UTC, ronrest commented on seerpy/seerpy.py
> +            iteration, so we set `object_path=["user"]`. But we actually want
Agreed, it was a little confusing. I rewrote it as follows, do you think it makes more sense now? 

```
e.g. We may be interested in the surveys for a user, while keeping
information about the user. The hierarchy will look something like
["user", "surveys"]. At the "user" level, it contains the user
information which we want to keep, so we set `object_path=["user"]`.
But we cannot iterate at this level, we want to iterate at the
"surveys" level, so we set `iteration_path=["surveys"]`
```

2021-04-08 00:15 UTC, ronrest commented on seerpy/seerpy.py
> +            max number of items to return. In the case of queries containing
fixed

2021-04-08 00:15 UTC, ronrest commented on seerpy/seerpy.py
> +        variable_values = deepcopy(variable_values) # prevent local changes affecting external one
fixed

2021-04-08 00:17 UTC, ronrest commented on seerpy/seerpy.py
> +        # response = self.execute_query(query_string)
fixed

2021-04-08 01:09 UTC, ronrest commented on seerpy/graphql.py
> +ORGANIZATION_BOOKINGS = """
1. added an assert statement as a temporary measure to protect against this while it remains non-paginated.
  ```assert (start_time is not None) and (end_time is not None), "start_time and end_time should not be None"```
2. This should maybe be done in a separate pull request. It will be a bigger task.

2021-04-08 01:12 UTC, ronrest commented on seerpy/seerpy.py
> +        # TODO: request changes to seer-api so we can perform pagination
We should treat the migration to resource schema as a separate pull request

2021-04-08 01:15 UTC, ronrest commented on seerpy/seerpy.py
> +    def get_all_bookings(self, organisation_id, start_time, end_time, include_cancelled=False):
The default in the graphql api was already `False`

![image](https://user-images.githubusercontent.com/10935663/113953589-807c2e80-985b-11eb-807f-baf594391bc8.png)

2021-04-08 04:35 UTC, norrishd commented on seerpy/seerpy.py
> +            iteration, so we set `object_path=["user"]`. But we actually want
Yep I get it now!

2021-04-08 04:50 UTC, norrishd commented on seerpy/seerpy.py
> +        # TODO: request changes to seer-api so we can perform pagination
Yep agreed! Matias is interested in this too.

2021-04-08 04:53 UTC, norrishd commented on seerpy/utils.py
> +    d: dict
Haha yeah variable naming, one of the two hard problems! Anything like `input_dict`, `nested_dict`, `dict_of_dict` seems fine to me.

2021-04-08 04:55 UTC, norrishd commented on seerpy/graphql.py
> +ORGANIZATION_BOOKINGS = """
Agreed, that should be a separate PR 👍

2021-04-08 05:53 UTC, ronrest commented on seerpy/seerpy.py
> +    def get_patients(self, party_id=None, limit=50, max_items=None):
You are correct. Setting it at a limit of `50` is painfullly slow. Running this at

Running this a few times at different `limit` values and averaging the time it takes to get ALL patients we get:

- At a value of `20,00` or above, it times out.
- At a value of `15,000` it sometimes times out.
- At a value of `10,000` it is the quickest, but could potentially time out for each page if the network is slow.
- At a value of `5,000`, it is only a bit slower than setting it to `10,000`, but potentially much safer.

| limit | time_secs | notes |
|------:|----------:| :--- |
| 15000 |   91.966 | high due to some timeouts |
| 10000 |   31.935 |  |
|  8000 |   33.132 |  |
|  7000 |   36.382 |  |
|  6000 |   38.010 |  |
|  5000 |   38.728 |  |
|  4000 |   41.985 |  |
|  3000 |   46.052 |  |
|  2000 |   46.223 |  |
|  1000 |   54.295 |  |
|   500 |  126.446 |  |
|   200 |  232.004 |  |
|   100 |  347.360 |  |
|    50 |  705.313 |  |


So setting limit to `5000`

2021-04-08 06:14 UTC, ronrest commented on seerpy/utils.py
> +    d: dict
changed it to `input_dict `

2021-04-08 06:16 UTC, ronrest commented
Ready for re-review. 

It passes all the tests locally. Not sure how to trigger the build-kite tests though.

2021-04-08 07:37 UTC, norrishd approved these changes
Looks great! Could you please also bump the minor version number in _setup.py_?

2021-04-08 07:37 UTC, norrishd commented on seerpy/seerpy.py
> +            max number of studies to return.
No worries if you don't change, but would be good to capitalise the "max" in the docstrings for all the functions that now have `max_items`

2021-04-08 22:37 UTC, ronrest commented on seerpy/seerpy.py
> +            max number of studies to return.
Ooops, i missed that. Fixed now :)

2021-04-11 23:49 UTC, ronrest commented
Bumped up the version number to 0.5.0

2021-04-14 11:25 UTC, norrishd approved these changes
Woop woop!

2021-04-16 04:30 UTC, matias-seer approved these changes
Looks good. thanks for making the effort to improves these functions

2021-04-16 06:20 UTC, merged