Add script to download medication adherence for HEP3 administrators
seermedical/seer-py pull request #148
Opened 2021-09-15 02:35 UTC by dkeden

_Quick_ script to download medication adherence to CSV for HEP3 administrators.

Added to Examples folder.

2021-09-16 04:39 UTC, pkaroly reviewed
This is looking good and working as expected. Happy to approve in the interest of merging and sending the research team something to work with. If they have feedback / require additional support we can iterate.

Would be good to update the minor comments I added (naming, and updated subdirectories) if you agree.

2021-09-16 04:39 UTC, pkaroly commented on Examples/hep3_medication_compliance_downloader.py
> +    python hep3_medication_compliance_downloader.py
Can we change the name to just 'medication_compliance_downloader' and remove all mention of HEP 3. There is nothing about this that is actually specific to the HEP 3 project right? Just in the interest of keeping our Examples folder clean and generalisable for other users where possible.

2021-09-16 04:39 UTC, pkaroly commented on Examples/hep3_medication_compliance_downloader.py
> +        os.makedirs(patient_dir, exist_ok=True)
Oops - when I said to put the individual patient data in sub-directories I didn't mean one sub-directory per patient, but one sub-directory for all the individual CSVs. So the output of this function will be a single overview CSV file (for all data) and a single directory, called something like 'Medication Adherence Per Patient' (containing the individual CSVs as previously). My thinking was that if lots of patients are generated I don't want to clutter up their run directory and make it unclear where to find the main CSV of interest, which is the one containing all data.

2021-09-17 03:39 UTC, EwanNurse commented
I keep getting HTTPS timeout errors on my machine. Don't know if it's just my internet.

2021-09-17 03:41 UTC, EwanNurse commented on Examples/hep3_medication_compliance_downloader.py
> +    date_range_text = f'{start_date_text}-{end_date_text}'
When I ran with a start and end date I was getting an errors because `start_date_text` / `end_date_text` wasn't defined. Should these be initialised at the top of the function?

2021-09-17 04:41 UTC, dkeden commented on Examples/hep3_medication_compliance_downloader.py
> +    date_range_text = f'{start_date_text}-{end_date_text}'
Yep! Absolutely. Thanks for catching this. Should work now.

2021-09-17 05:56 UTC, EwanNurse commented
I ran this using the start and end date flags, and it has worked as expected. All output files seem to have the information as described.

Note for testing I hard-coded the org to be the 'My Seizure Gauge' org as my permissions in 'Seer Medical' were likely borking the graphiql calls. This shouldn't be a problem for the ~100s of patients across the HEP3 orgs.

2021-09-17 06:01 UTC, EwanNurse requested changes
Pagination works correctly with typo changes, happy to merge after that change

2021-09-17 06:01 UTC, EwanNurse commented on Examples/medication_compliance_downloader.py
> +                                         variable_values={'pagionationLimit': pagination_limit},
```suggestion
                                         variable_values={'paginationLimit': pagination_limit},
```

2021-09-17 09:08 UTC, EwanNurse approved these changes

2021-09-17 10:40 UTC, merged