Add data downloader to Example scripts folder
seermedical/seer-py pull request #97
Opened 2020-08-24 02:39 UTC by dkeden

Data downloader scripts for Epilepsy Ecosystem. The file to run is `download_data.py` which uses scripts in the folder `download`. 

May need to modify file & folder names. Unsure if main file should replace the file `contestant_data_downloader.py`?

2020-08-24 04:40 UTC, bjdoyle requested changes

2020-08-24 04:40 UTC, bjdoyle commented on Examples/download_data.py
> +                this script at a later time.")
```suggestion
            print("ReadTimeoutError! Number of tries exceeded. Please re-run this script at a later"
                  " time.")
```

2020-08-24 04:40 UTC, bjdoyle commented on Examples/downloader/downloader.py
> +        channel_groups = self.client.get_all_study_metadata_dataframe_by_ids(
```suggestion
        channel_groups = self.client.get_all_study_metadata_dataframe_by_ids([self.study_id])
```

2020-08-24 04:40 UTC, bjdoyle commented on Examples/downloader/downloader.py
> +        channel_groups = self.client.get_all_study_metadata_dataframe_by_ids(
Actually could you run yapf over this?

2020-08-24 04:40 UTC, bjdoyle commented on Examples/downloader/downloader.py
> +        channels = {}
Something like this:
```suggestion
        return self.channel_groups[['channelGroups.name', 'channels.name']].drop_duplicates()
```
I haven't tested this, it may not be exactly right. This will return a dataframe, you can convert it to a list using .to_numpy().tolist()

2020-08-24 04:51 UTC, bjdoyle reviewed
Did Levin request that the output be in json? It's an interesting choice.
Could you run yapf over this for me, it's mostly good but there's a few things that makes me think it hasn't been run.
And get_channel_groups is more complicated than it needs to be.
Otherwise looks good.

2020-08-24 07:49 UTC, dkeden commented on Examples/downloader/downloader.py
> +        channels = {}
Ah! Okay, I've just added in a change

2020-08-24 07:58 UTC, dkeden commented
> Did Levin request that the output be in json? It's an interesting choice.
> Could you run yapf over this for me, it's mostly good but there's a few things that makes me think it hasn't been run.
> And get_channel_groups is more complicated than it needs to be.
> Otherwise looks good.

He didn't, but he wasn't happy with the size of the CSV files or the time it took to write each file despite using speedy vectorization w/ numpy arrays and writing to h5 file formats first, so I suggested JSON - just 'cause it's light-weight, fairly universal, MATLAB-friendly and approved by Kaggle.

Awesome, thanks. 

I think I've run yapf. Does this version look better?

2020-08-24 08:00 UTC, dkeden commented on Examples/downloader/downloader.py
> +        channel_groups = self.client.get_all_study_metadata_dataframe_by_ids(
Yup! I think I've done it this time?

2020-08-24 08:05 UTC, EwanNurse commented
Regarding naming, we'll need to keep `contest_data_downloader.py` just to keep supporting the NeuroVista download. Maybe rename to 'neurovista_contest_downloader.py' and add 'msg_' to the start of 'download_data.py'?

2020-08-24 08:19 UTC, dkeden commented
> Regarding naming, we'll need to keep `contest_data_downloader.py` just to keep supporting the NeuroVista download. Maybe rename to `neurovista_contest_downloader.py` and add 'msg_' to the start of `download_data.py`?

Sounds good, I'll make a change now

2020-08-24 09:02 UTC, bjdoyle requested changes
get_channels could still do with a modification

2020-08-24 22:08 UTC, dkeden commented on Examples/downloader/downloader.py
> +        return ([channel_group, channel] for channel_group, channel in zip(
Cool, didn't realise you could do this

2020-08-24 23:34 UTC, bjdoyle requested changes

2020-08-24 23:34 UTC, bjdoyle commented on Examples/downloader/downloader.py
>              channels['channelGroups.name'].tolist(), channels['channels.name'].tolist()))
But you also have to delete this line! (Sorry, I can't figure out how to get suggest change to encompass multiple lines)

2020-08-24 23:57 UTC, dkeden commented on Examples/downloader/downloader.py
>              channels['channelGroups.name'].tolist(), channels['channels.name'].tolist()))
Oh... sorry I was in speedy mode this morning

2020-08-24 23:59 UTC, dkeden commented on Examples/downloader/downloader.py
>              channels['channelGroups.name'].tolist(), channels['channels.name'].tolist()))
Should be good now

2020-08-25 00:49 UTC, bjdoyle approved these changes

2020-08-25 01:18 UTC, merged